repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/ JohnnyMorganz/stylua
    rev: v0.18.0
    hooks:
      - id: stylua-github
        args: ["--config-path", "stylua.toml"]

  - repo: https://github.com/lunarmodules/luacheck
    rev: v1.1.1
    hooks:
      - id: luacheck
        args: ["--config", ".luacheckrc"]

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
